# Object Oriented Programming in Python

This tutorial is a transcription of the Object Oriented Programming Lessons provided by the illustrious Corey Schafer on Youtube!


*   https://www.youtube.com/watch?v=ZDa-Z5JzLYM

## Lesson 1: Classes and Instances



### **Class**: a blue print for creating *instances*

In [0]:
class Roman: 
  pass

Each unique person will be an instance of the class **Roman**

For example:

In [0]:
Roman_1 = Roman()
Roman_2 = Roman()

print (Roman_1)
print (Roman_2)


### Instance variables: contains data that is unique to each instance

For example, name, bdate, email, enemies are instance variables

In [0]:
Roman_1.name = 'Marcus Tullius Cicero'
Roman_1.bdate = '106 BC'
Roman_1.email = 'procaelio@pigeon.com'
Roman_1.enemies = ['Mark Antony', 'Julius Caesar']
 

Roman_2.name = 'Publius Ovidius Naso'
Roman_2.bdate = '43 BC'
Roman_2.email = 'arsamatoria@pigeon.com'
Roman_2.enemies = ['Augustus Caesar']

print (Roman_1.name)
print (Roman_2.name)

As shown above, coding classes by hand is time intensive and error-prone

### Therefore, to set up classes automatically, we use a special method: init

```
  def __init__(self)
```

You can think of this method as "initialized" or as the constructor (as in other languages)

In [0]:
class Roman: 
  def __init__(self, name, bdate, email, enemies):
    self.name = name
    self.bdate = bdate
    self.email = email
    self.enemies = enemies
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)

### When we create methods within a class, they recieve the instance as the first argument automatically. By convention, we call the instance "self". Stick to convention, use self.



```
class Roman:
  def __init__(self, 
```


We will add to our code thusly:

```
class Roman: 
  def __init__(self, name, bdate, email, enemies):
    self.name = name
    self.bdate = bdate
    self.email = email
    self.enemies = ememies
```

By saying that **self ** is the instance, we mean that setting self.name = name in our code will set Roman_1 = Marcus Tullius Cicero, when we create our Roman objects, automatically. 

The name of the instance does not have to be the same for instance:



```
class Roman: 
  def __init__(self, name, bdate, email, enemies):
    self.fullname = name
    self.birthdate = bdate
    self.contact = email
    self.BFFs = ememies
```

But why would ya do that? Just keep it simple, stupid! Match init labels to the instance variables when possible. 

### Now when we create our instances of our employee class, we can pass through the data easier:



* When we create our instance, our Roman_1, there is no need to specify **self** now -- the instance is passed through automatically 
*   Data must be passed through in the same order it was encoded 


In [0]:
Roman_1 = Roman('Marcus Tullius Cicero', '106 BC', 'procaelio@pigeon.com', ['Mark Antony', 'Julius Caesar'])
Roman_2 = Roman('Publius Ovidius Naso', '43 BC', 'arsamatoria@pigeon.com', ['Augustus Caesar'])

print (Roman_1.enemies)
print (Roman_2.enemies)

['Mark Antony', 'Julius Caesar']
['Augustus Caesar']


When we pass through the information, the init method will be run through automatically. 


*   Roman_1 will be passed through as self. 
*   And then all the attributes will be mapped on to the instance variables. 

Now lets add methods to our class, such as displaying two factors together 



In [0]:
print ('{} {}'.format(Roman_1.name, Roman_1.bdate))

Marcus Tullius Cicero 106 BC


Let's write a function for displaying name & bdate


Simply replace the variable** Roman_1** with** self** to create the method and add it to our Roman class


```
  def name_date(self):
    return '{} {}'.format(self.name, self.bdate)
```



In [0]:
print(Roman_1.namedate())

Marcus Tullius Cicero 106 BC


Notice that we need extra parthenses () because this is a **method**, not an attribute

If we left them off, running the code would print the method not its product!

One common mistake is leaving the self instance off of the method, let's see what this does:



In [0]:
class Roman: 
  def __init__(self, name, bdate, email, enemies):
    self.name = name
    self.bdate = bdate
    self.email = email
    self.enemies = enemies
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
Roman_1 = Roman('Marcus Tullius Cicero', '106 BC', 'procaelio@pigeon.com', ['Mark Antony', 'Julius Caesar'])
Roman_2 = Roman('Publius Ovidius Naso', '43 BC', 'arsamatoria@pigeon.com', ['Augustus Caesar'])
  
print(Roman_1.namedate())


Marcus Tullius Cicero 106 BC


An error message is triggered! 



```
Type Error: namedate() takes 0 positional arguments but 1 was given" --> its missing a positional argument, self
```

The instancce, which is Roman_1 is getting passed automatically, meaning it then takes the first argument. We have to expect that instance argument in our method

We can also run these methods calling the class name itself, which tells us what exactly is happening in the background. When we run the class, we must pass through the instance as Roman_1. When we call the instance, Roman_1 and ask for the method, we do not need to pass through self, this is done automatically. In fact when we call on the instance, the code is essentially interpreted as calling upon the class, which then passes through the specified instance. This is why we must specify our methods with self as the first instance. This will be importance for inheritance. 


```
Roman_1.namedate()
```

does the same exact thing as 


```
Roman.namedate(Roman_1)

```

as shown below:

In [0]:
print(Roman.namedate(Roman_1))

Marcus Tullius Cicero 106 BC


## Lesson 2: Class variables 

### Class varibles: variables that are shared among all instances of a class . In contrast, instance variables are unique for each instance. 

Let's create an annual raise to our Romans, the amount can change for each Roman, but  its the same for percent for all.

In [0]:
class Roman: 
  def __init__(self, name, bdate, email, enemies, pay):
    self.name = name
    self.bdate = bdate
    self.email = email
    self.enemies = enemies
    self.pay = pay
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
  def apply_raise(self):
    self.pay = int (self.pay * 1.04)
  
Roman_1 = Roman('Marcus Tullius Cicero', '106 BC', 'procaelio@pigeon.com', ['Mark Antony', 'Julius Caesar'], 50000, )
Roman_2 = Roman('Publius Ovidius Naso', '43 BC', 'arsamatoria@pigeon.com', ['Augustus Caesar'], 60000)

print (Roman_1.pay)
Roman_1.apply_raise()
print (Roman_1.pay)

50000
52000


It worked. But there are a few short-comings.  First, it would be nice if we could access the raise amount by 


```
Roman_1.raise_amount
Roman.raise_amount
```

But the raise amount attribute doesn't currently exist so we can't see it's 4%. And what if we wanted to easily update the raise amount? We would have to change it manually, and if we used it in multiple calculations, we would have to laboriously copy&paste our update! 

### **We want to pull out the 4% and create a class variable:**


```
class Roman: 
  
  raise_amount = 1.04
  
  def apply_raise(self):
    self.pay = int (self.pay * raise_amount)
```

But this wouldn't work. As written, it would trigger 



```
Name error: name 'raise_amount' is not defined 
```

###**When we acesss these class variables, we need to access them through either the class itself or an instance of the class. **

```
  def apply_raise(self):
    self.pay = int (self.pay * Roman.raise_amount)
```


We can also write 

```
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
```


In [0]:
class Roman: 
  
  raise_amount = 1.04
  
  def __init__(self, name, bdate, email, enemies, pay):
    self.name = name
    self.bdate = bdate
    self.email = email
    self.enemies = enemies
    self.pay = pay
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
  
Roman_1 = Roman('Marcus Tullius Cicero', '106 BC', 'procaelio@pigeon.com', ['Mark Antony', 'Julius Caesar'], 60000, )
Roman_2 = Roman('Publius Ovidius Naso', '43 BC', 'arsamatoria@pigeon.com', ['Augustus Caesar'], 60000)

print (Roman_1.pay)
Roman_1.apply_raise()
print (Roman_1.pay)

60000
62400


When we check an attribute on an instance, it will first check if the instance contains that attribute. If it doesn't then, it will check whether the class or any class it inherits from contains that attribute. When we access our raise amount through our instances, they don't actually have that attribute themselves, they are accessing the class's raise_amount attribute. 

In [0]:
print (Roman.raise_amount)
print(Roman_1.raise_amount)
print(Roman_2.raise_amount)

1.04
1.04
1.04


We can tell exactly which attributes an instance has by using the following code



```
print(Roman_1.__dict__)
```

Thus proving that raise_amount is not an attribute of the instance. 

In [0]:
print(Roman_1.__dict__)

{'name': 'Marcus Tullius Cicero', 'bdate': '106 BC', 'email': 'procaelio@pigeon.com', 'enemies': ['Mark Antony', 'Julius Caesar'], 'pay': 52000}


When we investigate our Roman class, we find that raise_amount is an attribute of the class indeed.

In [0]:
print(Roman.__dict__)

{'__module__': '__main__', 'raise_amount': 1.04, '__init__': <function Roman.__init__ at 0x7f3960f0ed08>, 'namedate': <function Roman.namedate at 0x7f3960f0eea0>, 'apply_raise': <function Roman.apply_raise at 0x7f3960f0ebf8>, '__dict__': <attribute '__dict__' of 'Roman' objects>, '__weakref__': <attribute '__weakref__' of 'Roman' objects>, '__doc__': None}


### We can call upon the class to change its attribute raise_amount:

In [0]:
Roman.raise_amount = 1.05 

print (Roman.raise_amount)
print(Roman_1.raise_amount)
print(Roman_2.raise_amount)

1.05
1.05
1.05


### We can also change the attribute for a specific instance , in this case Roman_1:

In [0]:
Roman_1.raise_amount = 1.06 

print (Roman.raise_amount)
print(Roman_1.raise_amount)
print(Roman_2.raise_amount)

1.05
1.06
1.05


This is a little unexpected. It only affected one instance. 

**When we made this assignment, it created a raise_amount attribute within Roman_1's namespace**.  This is an important concept.  Roman_1 finds the attribute within its own namespace and returns that value -- 1.06, before going and searching the class. Roman_2 still carries the same default attribute of the class - 1.05.

If we print back out Roman_1's namespace, under the new assignment, we can see this:

In [0]:
print(Roman_1.__dict__)

{'name': 'Marcus Tullius Cicero', 'bdate': '106 BC', 'email': 'procaelio@pigeon.com', 'enemies': ['Mark Antony', 'Julius Caesar'], 'pay': 52000, 'raise_amount': 1.06}


This is all possible because of the nuance in the initial code: the decision whether to access the class variable (raise_amount) in the method (the pay calculation) through either the class itself (Roman) or an instance of the class (self)

By accessing the raise_amount using the instance of the class, we are able to change the amount for a single instance, if we want to. We will also allow any subclass to override this value, we will look at subclassing in a future lesson.

```
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
```

In [0]:
Roman_1.apply_raise()
print (Roman_1.pay)

Roman_2.apply_raise()
print (Roman_2.pay)

64896
62400


In other cases, it doesn't make sense to use self and allow the amount to vary for each instance.   For example, let's say we want to count how many Romans we have. The number should be the same for all instances of our class.


```
Roman.num_of_Rom += 1
```

We want to use Roman.num_of_Rom not self.num_of_Rom because we do not want it to vary. 

In [0]:
class Roman: 
  
  num_of_Rom = 0
  raise_amount = 1.04
  
  def __init__(self, name, bdate, email, enemies, pay):
    self.name = name
    self.bdate = bdate
    self.email = email
    self.enemies = enemies
    self.pay = pay
    
    Roman.num_of_Rom += 1
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
    

Roman_1 = Roman('Marcus Tullius Cicero', '106 BC', 'procaelio@pigeon.com', ['Mark Antony', 'Julius Caesar'], 60000, )
Roman_2 = Roman('Publius Ovidius Naso', '43 BC', 'arsamatoria@pigeon.com', ['Augustus Caesar'], 60000)

print (Roman.num_of_Rom)

2


The code printed 2 because it was incremented twice when we instantiated both of our Romans. If we moved it to before we instantiated our employees, it would print 0. 

## Lesson 3: Regular method, Classmethods and staticmethods

### Regular Methods:  automatically take the instance as the first argument, which we call by convention "self"

How can we change this so that it instead automatically takes the class as the first argument? We use **class methods**. To do this we add a decorator to the top **@classmethod**.  Decorators alter functionality of our method to where we recieve the class as our first argument instead of the instance. Just as with "self", there is a convention to call this "**cls**" We cannot use "class" as the variable name because that word already has a meaning in Python! It already was used to create a new class. Instead we will use cls as our class variable name.


```
@classmethod
def set_raise_amount (cls, amount)
  cls.raise_amount = amount

```

Now we can easily change the raise amount using our set_raise_amount method. It automatically accepts the class and accepts an amount. The reason the value updates to 1.05 is because we ran a set_raise_amout method, which is a class method, meaning we are working with a class instead of an instance. Thus, because we are performing a manipulation on a class variable, we need to create a class method. 


```
Roman.set_raise_amount(1.05)
```

We could also potentially run a class method from the instance. The outcome is the same, the change affects all instances. 

```
Roman_1.set_raise_amount(1.05)
```

In [0]:
class Roman: 
  
  num_of_Rom = 0
  raise_amount = 1.04
  
  def __init__(self, name, bdate, pay):
    self.name = name
    self.bdate = bdate
    self.pay = pay
    
    Roman.num_of_Rom += 1
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
    
  @classmethod
  def set_raise_amount (cls, amount):
    cls.raise_amount = amount

Roman_1 = Roman('Marcus Tullius Cicero', '106 BC', 60000, )
Roman_2 = Roman('Publius Ovidius Naso', '43 BC', 60000)

Roman.set_raise_amount(1.05)

print (Roman.raise_amount)
print(Roman_1.raise_amount)
print(Roman_2.raise_amount)

1.05
1.05
1.05


Class methods are also called alternative constructers. That means we can use the class methods to provide multiple ways of creating objects. For example, it can be used to automatically pass through a string to create an instances. 



```
cls(name, pay)
```

This line create our new Roman. Now that we've created our new Roman, we must also return it, so that it can recieve recieve the Roman object when it is called. 


```
return cls(name, pay)
```

So now our alternative constructer is done. This is what people mean when they say they use* class methods as alternative constructers*. 


In [0]:
class Roman: 
  
  num_of_Rom = 0
  raise_amount = 1.04
  
  def __init__(self, name, pay):
    self.name = name
    self.pay = pay
    
    Roman.num_of_Rom += 1
    
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
    
  @classmethod
  def set_raise_amount (cls, amount):
    cls.raise_amount = amount
    
  @classmethod
  def from_string (cls,Roman_str):
    name, pay = Roman_str.split('-')
    return cls(name, pay)

Roman_1 = Roman('Marcus Tullius Cicero', 60000, )
Roman_2 = Roman('Publius Ovidius Naso', 60000)

Roman.set_raise_amount(1.05)


Roman_str_1 = 'Livia Drusilla-60000'
Roman_str_2 = 'Tiberius Claudius Caesar-60000'

new_Roman_1 = Roman.from_string(Roman_str_1)
new_Roman_2 = Roman.from_string(Roman_str_2)


print(new_Roman_1.name)
print(new_Roman_2.name)
print(Roman.num_of_Rom)


Livia Drusilla
Tiberius Claudius Caesar
4


Static methods are often confused with class methods. Regular methods automatically pass the instance as the first argument (self). Class methods pass the class as the first argument (cls). 

###Static methods:  do not automatically pass either the instance OR the class. They behave just like normal functions. They are usually associated with classes because they have some logical association with class. 

Let's say we want a build a function that takes a date and automatically returns whether it is a workday. This does not depend on any instance or class variable. Thus we need to create a static method. To create it, we use a decorate, **@staticmethod**

In [0]:
class Roman: 
  
  num_of_Rom = 0
  raise_amount = 1.04
  
  def __init__(self, name, pay):
    self.name = name
    self.pay = pay
    
    Roman.num_of_Rom += 1
    
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
    
  @classmethod
  def set_raise_amount (cls, amount):
    cls.raise_amount = amount
    
  @classmethod
  def from_string (cls,Roman_str):
    name, pay = Roman_str.split('-')
    return cls(name, pay)
  
  @staticmethod
  def is_workday(day):
    if day.weekday() == 5 or day.weekday() == 6:
      return False
    return True

Roman_1 = Roman('Marcus Tullius Cicero', 60000, )
Roman_2 = Roman('Publius Ovidius Naso', 60000)

import datetime
my_date = datetime.date(2016, 7, 10)

print(Roman.is_workday(my_date))


False


Sometimes people write regular methods or class methods that actually should be static method. 

**One way to tell you method should be a static method is if you don't access the instance or class anywhere within the function. **

## Lesson 4: Inheritance - Creating Subclasses

### Inheritance: allows us to inherit attributes and methods from a parent classes

Subclasses get all the functionalities of their class, or add new functionality without affecting the parent class

For example, let's say we want to create patricians and plebs. They will have all the variables of our other Roman instances - name, bdate, pay but additional features. 

In [0]:
class Roman: 
  
  num_of_Rom = 0
  raise_amount = 1.04
  
  def __init__(self, name, bdate, pay):
    self.name = name
    self.bdate = bdate
    self.pay = pay
    
    Roman.num_of_Rom += 1
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
    
  @classmethod
  def set_raise_amount (cls, amount):
    cls.raise_amount = amount

class Patrician (Roman):
  pass
  
Patrician_1 = Patrician('Marcus Tullius Cicero', '106 BC', 60000, )
Patrician_2 = Patrician('Publius Ovidius Naso', '43 BC', 60000)

Roman.set_raise_amount(1.05)


print(help(Patrician))




Help on class Patrician in module __main__:

class Patrician(Roman)
 |  Method resolution order:
 |      Patrician
 |      Roman
 |      builtins.object
 |  
 |  Methods inherited from Roman:
 |  
 |  __init__(self, name, bdate, pay)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  apply_raise(self)
 |  
 |  namedate(self)
 |  
 |  ----------------------------------------------------------------------
 |  Class methods inherited from Roman:
 |  
 |  set_raise_amount(amount) from builtins.type
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Roman:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from Roman:
 |  
 |  num_of_Rom = 2
 |  
 |  raise_amount = 1.05

None


So now instead of creating two new Romans we create two new Patricians. We can now access the atrributes which were set in our parent Roman class. When we instantiated our patricians, it first looked at our Patrician class for our init method. However, we did not init in our Patrician class. Python works up the chain of inheritance until it finds the method it is looking for. This chain is called the** method resolutioin order. ** These are the places that Python searches for attributes and methods. 

If it does not find the method in the highest order class, it inherits the methods of the builtins object class. 

Now lets say we want to customize our subclass. Let's try changing our raise amount for our Patrician subclass from 4% to 10%

In [0]:
class Roman: 
  
  num_of_Rom = 0
  raise_amount = 1.04
  
  def __init__(self, name, bdate, pay):
    self.name = name
    self.bdate = bdate
    self.pay = pay
    
    Roman.num_of_Rom += 1
    
  def namedate(self):
    return '{} {}'.format(self.name, self.bdate)
  
  def apply_raise(self):
    self.pay = int (self.pay * self.raise_amount)
    
  @classmethod
  def set_raise_amount (cls, amount):
    cls.raise_amount = amount

class Patrician (Roman):
  raise_amount = 1.10
  
Patrician_1 = Patrician('Marcus Tullius Cicero', '106 BC', 60000, )
Patrician_2 = Patrician('Publius Ovidius Naso', '43 BC', 60000)

Roman.set_raise_amount(1.05)


print(Patrician_1.pay)
Patrician_1.apply_raise()
print(Patrician_1.pay)

60000
66000


Success, we lined Cicero's pockets! 

Now let's say we want to supply more information about our subclass than our parent class can handle. 